# Generated by Django 3.2.4 on 2021-06-19 16:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pack', '0002_auto_20210619_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='packs',
            name='num_packs',
            field=models.IntegerField(default=datetime.datetime(2021, 6, 19, 16, 44, 22, 119583, tzinfo=utc), max_length=10),
            preserve_default=False,
        ),
    ]
