# Generated by Django 3.2.4 on 2021-06-19 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pack', '0003_packs_num_packs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packs',
            name='num_packs',
        ),
    ]
