# Generated by Django 3.2.4 on 2021-06-19 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pack', '0005_packs_num_packs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packs',
            name='num_packs',
        ),
        migrations.RemoveField(
            model_name='packs',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='packs',
            name='cost_packs',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
            preserve_default=False,
        ),
    ]
