# Generated by Django 3.2.4 on 2021-06-19 17:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pack', '0006_auto_20210619_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='packs',
            name='num_packs',
            field=models.SmallIntegerField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='packs',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 6, 19, 17, 8, 58, 940541, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
